"""empty message

Revision ID: cf16b658d6d5
Revises: c5f7243fbcd6
Create Date: 2022-08-13 10:49:37.757294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf16b658d6d5'
down_revision = 'c5f7243fbcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('Artist_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('Venue_id', sa.String(), nullable=True))
    op.add_column('Shows', sa.Column('Venue_name', sa.String(length=120), nullable=True))
    op.add_column('Shows', sa.Column('Artist_name', sa.String(length=120), nullable=True))
    op.add_column('Shows', sa.Column('Artist_image_link', sa.String(length=500), nullable=True))
    op.drop_column('Shows', 'state')
    op.drop_column('Shows', 'image_link')
    op.drop_column('Shows', 'city')
    op.drop_column('Shows', 'id')
    op.drop_column('Shows', 'phone')
    op.drop_column('Shows', 'name')
    op.drop_column('Shows', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Shows_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('Shows', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'Artist_image_link')
    op.drop_column('Shows', 'Artist_name')
    op.drop_column('Shows', 'Venue_name')
    op.drop_column('Shows', 'Venue_id')
    op.drop_column('Shows', 'Artist_id')
    # ### end Alembic commands ###
